config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'tweets#index'
  resources :tweets do
    resources :comments, only: [:create]
  end
  resources :contacts, only: [:new,:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id])
    redirect_to "/tweets/#{@comment.tweet.id}"
  end
  
  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
  end
  
  def create
    @contacts = Contact.create(contact_params)
  end

  private
  def contact_params
    params.permit(:name, :address, :text)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  def index
    @tweets = Tweet.order("created_at ASC").page(params[:page]).per(5)
  end
  
  def new
    
  end
  
  def create
    Tweet.create(tweet_params)
  end
  
  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
  end
  
  private
  def tweet_params
    params.permit(:name, :images, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/contacts/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      <%= @contacts.name %>様</br>
      以下の内容にてお問い合わせを承りました。</br>
    </h3>
    <p><%= @contacts.text %></p>
    <a class="btn" href="/tweets">トップページへ戻る</a>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_tag('/contacts', method: :post) do %>
      <h3>
        サービスに関するお問い合わせ</br>
      </h3>
      <input type="text" name="name" placeholder="お名前を入力してください">
      <input type="text" name="address" placeholder="メールアドレスを入力してください">
      <textarea name="text" placeholder="お問い合わせ内容を入力してください" rows="10" cols="30"></textarea>
      <input type="submit" value="内容を送信">
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>hacken</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Hacken</a></h1>
        <div class="user_nav grid-6">
            <%= link_to "投稿する",  new_tweet_path, class: "post" %>
            <%= link_to "問い合わせ",  new_contact_path, class: "post" %>
        </div>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright Hacken 2020.
      </p>
    </footer>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="content_post" style="background-image: url(<%= tweet.image %>);">
  <div class="more">
    <span><%= image_tag 'arrow_top.png' %></span>
    <ul class="more_list">
      <li>
        <%= link_to '詳細', "/tweets/#{tweet.id}", method: :get %>
      </li>
      <li>
        <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
      </li>
    </ul>
  </div>
  <%= simple_format(tweet.text) %>
  <span class="name"><%= tweet.name %><br><%= tweet.created_at.to_s(:datetime_jp) %></span>
  
</div>

app/views/tweets/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/tweets">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="contents row" >
  <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet } %>
  <% end %>
  <%= paginate(@tweets) %>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_tag('/tweets', method: :post) do %>
      <h3>
        投稿する
      </h3>
      <input type="text" name="name" placeholder="ニックネーム">
      <input type="text" name="image" placeholder="画像URL">
      <textarea name="text" placeholder="テキストを入力してください" rows="10" cols="30"></textarea>
      <input type="submit" value="SEND">
    <% end %>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="contents row">
  <div class="content_post" style="background-image: url(<%= @tweet.image %>);">
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
          </li>
        </ul>
      </div>
    <%= simple_format(@tweet.text) %>
    <span class="name"><%= @tweet.name %></span>
  </div>
  <div class="container">
    <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
      <textarea name="text" placeholder="コメントする" rows="2" cols="30"></textarea>
      <input type="submit" value="SENT">
    <% end %>
    <div class="comments">   
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>